name: Deploy to zsc.guru

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Archive project files
        run: |
          tar -czf project.tar.gz *

      - name: Upload project files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'project.tar.gz'
          target: ${{secrets.DEPLOY_PATH}}

      - name: Run node server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH="$HOME/.volta/bin:$PATH"
            export PATH="$HOME/.local/share/pnpm:$PATH"
            export DATABASE_URL="${{ secrets.DATABASE_URL }}"
            cd ${{secrets.DEPLOY_PATH}}
            tar -xzf project.tar.gz
            pnpm i
            pnpm build:prod
            pnpm pm2
